# Generated by Django 6.0.6 on 2026-06-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='content',
            field=models.TextField(),
        ),
    ]
