# Generated by Django 6.0.5 on 2026-06-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_refer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysqlapp.customer')),
                ('product_refer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysqlapp.product')),
            ],
        ),
    ]
