# Generated by Django 6.0.5 on 2026-06-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_department_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('course', models.ManyToManyField(to='orm.course')),
            ],
        ),
    ]
